spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: ["*"]
            allowedMethods: ["GET","POST","PUT","DELETE","OPTIONS"]
            allowedHeaders: ["*"]
            allowCredentials: true
      routes:
        - id: user-service-auth
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - AddRequestHeader=X-Gateway, axiom

        - id: user-service-users
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/users/**,/api/v1/watchlists/**
          filters:
            - AddRequestHeader=X-Gateway, axiom

        - id: stock-data-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/stocks/**,/api/v1/market/**
          filters:
            - AddRequestHeader=X-Gateway, axiom

        - id: analysis-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/analysis/**,/api/v1/signals/**
          filters:
            - AddRequestHeader=X-Gateway, axiom

server:
  port: 8080

jwt:
  secret: axiom_jwt_secret_change_in_prod_min_256_bits_long_enough

management:
  endpoints:
    web:
      exposure:
        include: health,info

