spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: ["*"]
            allowedMethods: ["GET","POST","PUT","DELETE","OPTIONS"]
            allowedHeaders: ["*"]
            allowCredentials: true
      routes:
        - id: user-service-auth
          uri: ${USER_SERVICE_URL}
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - AddRequestHeader=X-Gateway, axiom

        - id: user-service-users
          uri: ${USER_SERVICE_URL}
          predicates:
            - Path=/api/v1/users/**,/api/v1/watchlists/**
          filters:
            - AddRequestHeader=X-Gateway, axiom

        - id: stock-data-service
          uri: ${STOCK_DATA_SERVICE_URL}
          predicates:
            - Path=/api/v1/stocks/**,/api/v1/market/**
          filters:
            - AddRequestHeader=X-Gateway, axiom

        - id: analysis-service
          uri: ${ANALYSIS_SERVICE_URL}
          predicates:
            - Path=/api/v1/analysis/**,/api/v1/signals/**
          filters:
            - AddRequestHeader=X-Gateway, axiom

server:
  port: ${PORT:8080}

jwt:
  secret: ${JWT_SECRET}

